version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/tmp
      # socketファイルの共有
      - sockets:/app/tmp/sockets
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    security_opt:
      - seccomp:unconfined
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    #socketファイルの共有
    volumes: 
      - sockets:/app/tmp/sockets
    depends_on:
      - app

volumes:
  db-data:
  sockets:
